### ISSUE TITLE
Add suport for metric aliasing

### ISSUE THREAD

**Issue by mrares** [grobian/carbonserver#15]
I find it necessary to group metrics by a dimension and, bar duplicating metrics, there is no way of aliasing metrics e.g.:

We have the following space:
servers.<server_name>.<metric> 

Desired, separate space:
databases.<server_name>.<metric>
(where this is a subset of the servers namespace)

Obviously this would be a duplication of the servers space which is redundant, it would be much better if it were possible to submit configuration for aliasing:

databases.<server_name> -> servers.<server_name>

making the databases.<server_name> space virtual.

**Comment by dgryski** [comment]
Is this handled by https://github.com/dgryski/carbonzipper/tree/dynaq ?

**Comment by grobian** [comment]
yeah, so let's close this ticket

**Comment by drawks** [comment]
I'm not sure it is clear from the link to carbonzipper how it addresses this problem. Can someone either spell this out a little bit better and/or update the docs at https://github.com/dgryski/carbonzipper/tree/dynaq to more clearly explain how it solves this problem? The readme there is pretty sparse and doesn't include any example config for the "json file loaded at startup"

**Comment by grobian** [comment]
Ah yes, I see.  DynaQ is a work in progress, where we will support this kind of metric aliasing based on arbitrary configuration/implementation.  It isn't in a usable state yet.

**Comment by dgryski** [comment]
@drawks The idea is that carbonzipper can support "dynamic queries"; rather than having these aliases handled on the carbonserver side, we create a fake metric prefix that carbonzipper knows to send off to an external service.  The externals service parsing the query-that-looks-like-a-metric and returns a list of *new* metrics to retrieve.  In our current prototype (internal, but supported by public code), we're querying a json file that has been extracted from our internal server directory which knows things like the current status of a server, data center location, etc.  This is the general framework by which we would add alias support.

**Comment by drawks** [comment]
So if this is a work in process which isn't released yet is it not a bit premature to mark this issue closed?

**Comment by grobian** [comment]
I closed it because it's not going to get implemented/fixed here.  I'm also ok with keeping this one open until there is something in the zipper available, if that's more preferable.
